export const STORE_NAME = 'wpuf/subscriptions';

export const ACTION_TYPES = {
    SET_ITEMS: 'SET_ITEMS',
    SET_IS_LOADING: 'SET_IS_LOADING',
    SET_IS_UPDATING: 'SET_IS_UPDATING',
    SET_IS_DIRTY: 'SET_IS_DIRTY',
    SET_IS_UNSAVED_POPUP_OPEN: 'SET_IS_UNSAVED_POPUP_OPEN',
    SET_CURRENT_STATUS: 'SET_CURRENT_STATUS',
    SET_ITEM: 'SET_ITEM',
    SET_ITEM_COPY: 'SET_ITEM_COPY',
    SET_ERRORS: 'SET_ERRORS',
    SET_UPDATE_ERROR: 'SET_UPDATE_ERROR',
    SET_COUNTS: 'SET_COUNTS',
    SET_TAXONOMY_RESTRICTION: 'SET_TAXONOMY_RESTRICTION',
    SET_TAXONOMY_VIEW_RESTRICTION: 'SET_TAXONOMY_VIEW_RESTRICTION',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    MODIFY_ITEM: 'MODIFY_ITEM',
    RESET_ERRORS: 'RESET_ERRORS',
};
