<?php

namespace WeDevs\Wpuf\TwoFactor;

/**
 * Read/write helpers for per-user 2FA state
 *
 * Centralizes user-meta keys so the rest of the code never deals with
 * raw meta strings, and keys every entry by method id so multiple
 * methods (TOTP, Email OTP, SMS OTP) coexist without collisions.
 *
 * Five families of state:
 *
 *   - **Active method state** — `_wpuf_2fa_method_{id}_secret`,
 *     `_wpuf_2fa_method_{id}_enrolled_at`, `_wpuf_2fa_method_{id}_state`.
 *     `secret` is encrypted at rest (TOTP base32 key, future credentials).
 *     `state` is an opaque JSON blob the method reads and writes freely
 *     (TOTP last-accepted step, Email OTP resend counter, etc.).
 *
 *   - **Pending enrollment** — transient `wpuf_2fa_pending_{id}_{user}`.
 *     The candidate state held during the start→confirm round trip.
 *     Encrypted; expires after `PENDING_TTL`.
 *
 *   - **Issued codes** — transient `wpuf_2fa_issued_{id}_{user}`. The
 *     hashed one-time code generated by `issue_challenge()` for methods
 *     that need it (Email OTP, SMS OTP). Hash-only — `verify_issued_code()`
 *     checks via `password_verify()`. TTL is filterable via
 *     `wpuf_2fa_issued_code_ttl` (default 300s).
 *
 *   - **Audit log** — `_wpuf_2fa_audit_log`. Cross-method, capped at
 *     `AUDIT_LIMIT` entries. Each entry: `{ method_id, action, actor_id,
 *     timestamp, context }`.
 *
 * @since WPUF_SINCE
 */
class User_Storage {

    const META_AUDIT_LOG = '_wpuf_2fa_audit_log';

    const META_METHOD_PREFIX        = '_wpuf_2fa_method_';
    const META_METHOD_SECRET_SUFFIX = '_secret';
    const META_METHOD_ENROLLED_AT   = '_enrolled_at';
    const META_METHOD_STATE_SUFFIX  = '_state';

    const TRANSIENT_PENDING_PREFIX = 'wpuf_2fa_pending_';
    const TRANSIENT_ISSUED_PREFIX  = 'wpuf_2fa_issued_';

    const PENDING_TTL = 30 * MINUTE_IN_SECONDS;
    const AUDIT_LIMIT = 10;

    /** @var Crypto */
    private $crypto;

    public function __construct( Crypto $crypto ) {
        $this->crypto = $crypto;
    }

    /* ------------------------------------------------------------------
     * Active method state
     * ------------------------------------------------------------------ */

    /**
     * Persist the encrypted active credential for a method and stamp the
     * enrollment time. This is the atomic "user is now enrolled" call.
     *
     * @param int    $user_id
     * @param string $method_id
     * @param string $plaintext_secret
     */
    public function set_method_secret( $user_id, $method_id, $plaintext_secret ) {
        update_user_meta(
            $user_id,
            $this->meta_secret_key( $method_id ),
            $this->crypto->encrypt( $plaintext_secret )
        );
        update_user_meta(
            $user_id,
            $this->meta_enrolled_at_key( $method_id ),
            time()
        );
    }

    /**
     * @param int    $user_id
     * @param string $method_id
     *
     * @return string|null Plaintext secret, or null if not enrolled (or
     *                     AUTH_KEY rotated and ciphertext is unreadable).
     */
    public function get_method_secret( $user_id, $method_id ) {
        $payload = get_user_meta( $user_id, $this->meta_secret_key( $method_id ), true );

        if ( ! $payload ) {
            return null;
        }

        return $this->crypto->decrypt( $payload );
    }

    /**
     * @return int|null Unix timestamp, or null if not enrolled.
     */
    public function get_method_enrolled_at( $user_id, $method_id ) {
        $ts = (int) get_user_meta( $user_id, $this->meta_enrolled_at_key( $method_id ), true );

        return $ts ? $ts : null;
    }

    /**
     * Opaque per-method state. The method owns the shape — TOTP stores
     * `[ 'last_step' => int ]`, Email OTP can store `[ 'resend_count' =>
     * int, 'last_send' => int ]`. Always returns an array (empty if
     * never written).
     *
     * @param int    $user_id
     * @param string $method_id
     */
    public function get_method_state( $user_id, $method_id ): array {
        $state = get_user_meta( $user_id, $this->meta_state_key( $method_id ), true );

        return is_array( $state ) ? $state : [];
    }

    /**
     * @param int    $user_id
     * @param string $method_id
     * @param array  $state
     */
    public function set_method_state( $user_id, $method_id, array $state ) {
        update_user_meta( $user_id, $this->meta_state_key( $method_id ), $state );
    }

    /**
     * Tear down all state for a method on this user — secret, enrolled
     * timestamp, opaque state, pending transient, issued-code transient.
     * Called by `Method_Interface::reset()` implementations.
     *
     * @param int    $user_id
     * @param string $method_id
     */
    public function clear_method( $user_id, $method_id ) {
        delete_user_meta( $user_id, $this->meta_secret_key( $method_id ) );
        delete_user_meta( $user_id, $this->meta_enrolled_at_key( $method_id ) );
        delete_user_meta( $user_id, $this->meta_state_key( $method_id ) );
        $this->clear_pending_method( $user_id, $method_id );
        $this->clear_issued_code( $user_id, $method_id );
    }

    /* ------------------------------------------------------------------
     * Pending enrollment (start → confirm)
     * ------------------------------------------------------------------ */

    /**
     * Park a candidate secret in a transient during enrollment. The
     * active secret (if any) stays valid until confirmation succeeds —
     * users who restart enrollment don't lose their existing 2FA mid-flight.
     *
     * @param int    $user_id
     * @param string $method_id
     * @param string $plaintext_secret
     */
    public function set_pending_method( $user_id, $method_id, $plaintext_secret ) {
        set_transient(
            $this->pending_transient_key( $user_id, $method_id ),
            $this->crypto->encrypt( $plaintext_secret ),
            self::PENDING_TTL
        );
    }

    /**
     * @return string|null
     */
    public function get_pending_method( $user_id, $method_id ) {
        $payload = get_transient( $this->pending_transient_key( $user_id, $method_id ) );

        if ( ! $payload ) {
            return null;
        }

        return $this->crypto->decrypt( $payload );
    }

    public function clear_pending_method( $user_id, $method_id ) {
        delete_transient( $this->pending_transient_key( $user_id, $method_id ) );
    }

    /* ------------------------------------------------------------------
     * Issued codes (Email OTP, SMS OTP)
     * ------------------------------------------------------------------ */

    /**
     * Store a hash of an issued one-time code. Hashing (not encryption)
     * because we only ever need to know if a submitted code matches —
     * we never need the plaintext back. A DB leak yields hashes that
     * are useless to the attacker.
     *
     * One code per (user, method) at a time. A new call replaces any
     * existing pending code. TTL is filterable via
     * `wpuf_2fa_issued_code_ttl`.
     *
     * @param int    $user_id
     * @param string $method_id
     * @param string $code
     * @param int    $ttl Seconds until the code expires.
     */
    public function set_issued_code( $user_id, $method_id, $code, $ttl ) {
        set_transient(
            $this->issued_transient_key( $user_id, $method_id ),
            password_hash( (string) $code, PASSWORD_DEFAULT ),
            (int) $ttl
        );
    }

    /**
     * Check a submitted code against the stored hash. On match, the
     * stored code is consumed (one-time use) — a replay returns false.
     *
     * @param int    $user_id
     * @param string $method_id
     * @param string $submitted
     */
    public function verify_issued_code( $user_id, $method_id, $submitted ): bool {
        $hash = get_transient( $this->issued_transient_key( $user_id, $method_id ) );

        if ( ! $hash ) {
            return false;
        }

        if ( ! password_verify( (string) $submitted, $hash ) ) {
            return false;
        }

        // One-time use.
        $this->clear_issued_code( $user_id, $method_id );

        return true;
    }

    public function clear_issued_code( $user_id, $method_id ) {
        delete_transient( $this->issued_transient_key( $user_id, $method_id ) );
    }

    /* ------------------------------------------------------------------
     * Audit log
     * ------------------------------------------------------------------ */

    /**
     * Append an audit entry. Rolling list capped at `AUDIT_LIMIT`.
     *
     * @param int    $user_id   Subject of the action.
     * @param string $method_id Method involved (e.g. 'totp'). Empty for
     *                          method-agnostic events (rare).
     * @param string $action    e.g. 'enrolled', 'admin_reset',
     *                          'self_disable', 'challenge_issue_failed'.
     * @param int    $actor_id  User ID that performed the action.
     * @param array  $context   Optional free-form metadata (error
     *                          messages, etc.). Kept short — audit log
     *                          is for ops visibility, not telemetry.
     */
    public function append_audit( $user_id, $method_id, $action, $actor_id, array $context = [] ) {
        $log   = $this->get_audit_log( $user_id );
        $log[] = [
            'method_id' => (string) $method_id,
            'action'    => (string) $action,
            'actor_id'  => (int) $actor_id,
            'timestamp' => time(),
            'context'   => $context,
        ];

        if ( count( $log ) > self::AUDIT_LIMIT ) {
            $log = array_slice( $log, -self::AUDIT_LIMIT );
        }

        update_user_meta( $user_id, self::META_AUDIT_LOG, $log );
    }

    /**
     * @return array<int, array{method_id:string, action:string, actor_id:int, timestamp:int, context:array}>
     */
    public function get_audit_log( $user_id ): array {
        $log = get_user_meta( $user_id, self::META_AUDIT_LOG, true );

        return is_array( $log ) ? $log : [];
    }

    /* ------------------------------------------------------------------
     * Internals
     * ------------------------------------------------------------------ */

    private function meta_secret_key( $method_id ): string {
        return self::META_METHOD_PREFIX . $method_id . self::META_METHOD_SECRET_SUFFIX;
    }

    private function meta_enrolled_at_key( $method_id ): string {
        return self::META_METHOD_PREFIX . $method_id . self::META_METHOD_ENROLLED_AT;
    }

    private function meta_state_key( $method_id ): string {
        return self::META_METHOD_PREFIX . $method_id . self::META_METHOD_STATE_SUFFIX;
    }

    private function pending_transient_key( $user_id, $method_id ): string {
        return self::TRANSIENT_PENDING_PREFIX . $method_id . '_' . (int) $user_id;
    }

    private function issued_transient_key( $user_id, $method_id ): string {
        return self::TRANSIENT_ISSUED_PREFIX . $method_id . '_' . (int) $user_id;
    }
}
