export const STORE_NAME = 'wpuf/settings';

export const ACTION_TYPES = {
    SET_DATA: 'SET_DATA',
    SET_IS_LOADING: 'SET_IS_LOADING',
    SET_IS_SAVING: 'SET_IS_SAVING',
    SET_IS_DIRTY: 'SET_IS_DIRTY',
    SET_ACTIVE_TAB: 'SET_ACTIVE_TAB',
    SET_VALUE: 'SET_VALUE',
    SET_VALUES: 'SET_VALUES',
    SET_EXTRA_VALUE: 'SET_EXTRA_VALUE',
    SET_EXTRA_SAVED: 'SET_EXTRA_SAVED',
    SET_SEARCH: 'SET_SEARCH',
    SET_ERROR: 'SET_ERROR',
    DISCARD: 'DISCARD',
};
